hmrc/self-assessment-api

- test/uk/gov/hmrc/selfassessmentapi/MongoEmbeddedDatabase.scala
This prevents an annoying pop-up from appear when running on my Mac:
> Only have embedded mongo listen on the loopback interface during tests.

- app/uk/gov/hmrc/selfassessmentapi/repositories/domain/MongoLiability.scala
- app/uk/gov/hmrc/selfassessmentapi/repositories/domain/TaxBand.scala
- app/uk/gov/hmrc/selfassessmentapi/services/live/calculation/steps/PersonalSavingsAllowance.scala
- project/MicroServiceBuild.scala
- test/uk/gov/hmrc/selfassessmentapi/Generators.scala
- test/uk/gov/hmrc/selfassessmentapi/repositories/domain/TaxBandSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/services/live/calculation/steps/PersonalSavingsAllowanceSpec.scala
Calculation is stored in a temporary field and should be refactored to
be returned within the nilRate tax band of the savings income.
> [MTDSA-426] Implement calculation step for personal savings allowance

- .travis.yml
- Run test and func:test in parallel
- cache more directories for dependencies
> MTDSA-521 - travis config

- app/uk/gov/hmrc/selfassessmentapi/controllers/HalSupport.scala
- app/uk/gov/hmrc/selfassessmentapi/controllers/live/SourceController.scala
- app/uk/gov/hmrc/selfassessmentapi/controllers/sandbox/SummaryController.scala
> [MTDSA-523] [DM] Use same feature switched source links in live and sandbox

- app/uk/gov/hmrc/selfassessmentapi/config/FeatureSwitch.scala
- app/uk/gov/hmrc/selfassessmentapi/controllers/live/selfemployment/SelfEmploymentSourceHandler.scala
- app/uk/gov/hmrc/selfassessmentapi/controllers/live/unearnedincome/UnearnedIncomeSourceHandler.scala
- app/uk/gov/hmrc/selfassessmentapi/domain/Liability.scala
- app/uk/gov/hmrc/selfassessmentapi/domain/package.scala
- app/uk/gov/hmrc/selfassessmentapi/domain/ukproperty/Allowances.scala
- app/uk/gov/hmrc/selfassessmentapi/repositories/domain/AmountHolder.scala
- app/uk/gov/hmrc/selfassessmentapi/repositories/domain/MongoLiability.scala
- app/uk/gov/hmrc/selfassessmentapi/repositories/domain/MongoSelfEmployment.scala
- app/uk/gov/hmrc/selfassessmentapi/repositories/domain/MongoUKProperties.scala
- app/uk/gov/hmrc/selfassessmentapi/services/live/calculation/LiabilityCalculator.scala
- app/uk/gov/hmrc/selfassessmentapi/services/live/calculation/LiabilityService.scala
- app/uk/gov/hmrc/selfassessmentapi/services/live/calculation/steps/CalculationStep.scala
- app/uk/gov/hmrc/selfassessmentapi/services/live/calculation/steps/SelfEmploymentProfitCalculation.scala
- app/uk/gov/hmrc/selfassessmentapi/services/live/calculation/steps/TotalIncomeCalculation.scala
- app/uk/gov/hmrc/selfassessmentapi/services/live/calculation/steps/UKPropertyProfitCalculation.scala
- func/uk/gov/hmrc/selfassessmentapi/live/LiabilityControllerSpec.scala
- func/uk/gov/hmrc/selfassessmentapi/sandbox/LiabilityControllerSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/EmploymentSugar.scala
- test/uk/gov/hmrc/selfassessmentapi/SelfEmploymentSugar.scala
- test/uk/gov/hmrc/selfassessmentapi/repositories/domain/MongoLiabilitySpec.scala
- test/uk/gov/hmrc/selfassessmentapi/services/live/calculation/LiabilityServiceSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/services/live/calculation/steps/IncomeTaxReliefCalculationSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/services/live/calculation/steps/SelfEmploymentProfitCalculationSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/services/live/calculation/steps/TotalIncomeCalculationSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/services/live/calculation/steps/UKPropertyProfitCalculationSpec.scala
- Removed lossBroughtForward from SelfEmploymentIncome as it is not be returned as a part of liability calculation.
- Updated the total income calculation to take UK property income into account.
- Updated the IncomeTaxRelief calculation to take UK property tax into account.
> [SA][MDTSA-445] - Add calculation of UK property tax.

- app/uk/gov/hmrc/selfassessmentapi/domain/Liability.scala
- app/uk/gov/hmrc/selfassessmentapi/domain/package.scala
- app/uk/gov/hmrc/selfassessmentapi/domain/selfemployment/Allowances.scala
- app/uk/gov/hmrc/selfassessmentapi/repositories/domain/MongoLiability.scala
- app/uk/gov/hmrc/selfassessmentapi/repositories/domain/MongoSelfEmployment.scala
- app/uk/gov/hmrc/selfassessmentapi/repositories/domain/MongoUKProperties.scala
- app/uk/gov/hmrc/selfassessmentapi/services/live/calculation/steps/IncomeTaxReliefCalculation.scala
- app/uk/gov/hmrc/selfassessmentapi/services/live/calculation/steps/SelfEmploymentProfitCalculation.scala
- app/uk/gov/hmrc/selfassessmentapi/services/live/calculation/steps/UKPropertyProfitCalculation.scala
- func/uk/gov/hmrc/selfassessmentapi/live/LiabilityControllerSpec.scala
- func/uk/gov/hmrc/selfassessmentapi/sandbox/LiabilityControllerSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/SelfEmploymentSugar.scala
- test/uk/gov/hmrc/selfassessmentapi/repositories/domain/MongoLiabilitySpec.scala
- test/uk/gov/hmrc/selfassessmentapi/services/live/calculation/steps/IncomeTaxReliefCalculationSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/services/live/calculation/steps/TotalIncomeCalculationSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/services/live/calculation/steps/UKPropertyProfitCalculationSpec.scala
- Update tests to ensure that total loss brought forward is capped to adjusted profit for UK properties.
> [MTDSA-445] Add capping on the total loss brought forward for UK properties.

- app/uk/gov/hmrc/selfassessmentapi/services/live/calculation/steps/IncomeTaxReliefCalculation.scala
- test/uk/gov/hmrc/selfassessmentapi/services/live/calculation/steps/IncomeTaxReliefCalculationSpec.scala
- Ensure that self employments are capped on a per-source basis.
- Add additional tests that verify this behaviour.
> [MTDSA-445] Fix error in the calculation of the loss brought forward for self employments.

- app/uk/gov/hmrc/selfassessmentapi/domain/Liability.scala
- app/uk/gov/hmrc/selfassessmentapi/repositories/domain/MongoLiability.scala
- app/uk/gov/hmrc/selfassessmentapi/repositories/domain/MongoUKProperties.scala
- app/uk/gov/hmrc/selfassessmentapi/repositories/domain/MongoUnearnedIncome.scala
- app/uk/gov/hmrc/selfassessmentapi/services/live/calculation/steps/TaxDeductedCalculation.scala
- func/uk/gov/hmrc/selfassessmentapi/live/LiabilityControllerSpec.scala
- func/uk/gov/hmrc/selfassessmentapi/sandbox/LiabilityControllerSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/SelfEmploymentSugar.scala
- test/uk/gov/hmrc/selfassessmentapi/repositories/domain/MongoLiabilitySpec.scala
- test/uk/gov/hmrc/selfassessmentapi/services/live/calculation/steps/TaxDeductedCalculationSpec.scala
- Modify the TaxDeductedCalculation step to take in to account the deduction from UK properties.
- Update LiabilityControllerSpec and TaxDeductedCalculationSpec to validate this new behaviour.
> [MTDSA-449] Calculate the tax deducted for UK properties.

- .gitignore
> Update .gitignore to exclude .ensime files.

- app/uk/gov/hmrc/selfassessmentapi/domain/Liability.scala
- app/uk/gov/hmrc/selfassessmentapi/domain/TaxYearProperties.scala
- app/uk/gov/hmrc/selfassessmentapi/domain/pensioncontribution/PensionContribution.scala
- app/uk/gov/hmrc/selfassessmentapi/repositories/domain/MongoLiability.scala
- app/uk/gov/hmrc/selfassessmentapi/services/live/calculation/LiabilityCalculator.scala
- app/uk/gov/hmrc/selfassessmentapi/services/live/calculation/LiabilityService.scala
- app/uk/gov/hmrc/selfassessmentapi/services/live/calculation/steps/CalculationStep.scala
- app/uk/gov/hmrc/selfassessmentapi/services/live/calculation/steps/RetirementAnnuityContractCalculation.scala
- conf/application.conf
- func/uk/gov/hmrc/selfassessmentapi/live/LiabilityControllerSpec.scala
- func/uk/gov/hmrc/selfassessmentapi/sandbox/LiabilityControllerSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/SelfEmploymentSugar.scala
- test/uk/gov/hmrc/selfassessmentapi/repositories/domain/MongoLiabilitySpec.scala
- test/uk/gov/hmrc/selfassessmentapi/services/live/calculation/LiabilityServiceSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/services/live/calculation/steps/RetirementAnnuityContractCalculationSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/services/live/calculation/steps/TotalAllowancesAndReliefsCalculationSpec.scala
- Add a new calculation step that computer the total amount paid in to a retirement annuity contract.
- Add tests that check the functionality and integration of the retirement annuity contract calculation.
> [MTDSA-314] Calculate payments into a retirement annuity contract.

- app/uk/gov/hmrc/selfassessmentapi/domain/Liability.scala
- app/uk/gov/hmrc/selfassessmentapi/domain/ukproperty/TaxPaid.scala
- app/uk/gov/hmrc/selfassessmentapi/repositories/domain/MongoLiability.scala
- app/uk/gov/hmrc/selfassessmentapi/repositories/domain/MongoUKProperties.scala
- app/uk/gov/hmrc/selfassessmentapi/services/live/calculation/steps/TaxDeductedForUkPropertiesCalculation.scala
- test/uk/gov/hmrc/selfassessmentapi/UkPropertySugar.scala
- test/uk/gov/hmrc/selfassessmentapi/repositories/domain/MongoLiabilitySpec.scala
- test/uk/gov/hmrc/selfassessmentapi/services/live/calculation/steps/TaxDeductedForUkPropertiesCalculationSpec.scala
- Update tests to check for the new JSON format.
- Minor style improvements
> [MTDSA-449] Update the format of the JSON output for UK property tax deductions.

- app/uk/gov/hmrc/selfassessmentapi/controllers/ErrorResponses.scala
- app/uk/gov/hmrc/selfassessmentapi/domain/ErrorCode.scala
- app/uk/gov/hmrc/selfassessmentapi/services/live/calculation/LiabilityService.scala
- app/uk/gov/hmrc/selfassessmentapi/services/live/calculation/steps/TaxDeductedFromUkTaxPaidForEmploymentsCalculation.scala
- func/uk/gov/hmrc/selfassessmentapi/live/LiabilityControllerSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/services/live/calculation/steps/TaxDeductedFromUkTaxPaidForEmploymentsCalculationSpec.scala
> [MTDSA-434] Fix error response to be in accordance with the existing format for

- app/uk/gov/hmrc/selfassessmentapi/domain/pensioncontribution/PensionContribution.scala
- app/uk/gov/hmrc/selfassessmentapi/domain/pensioncontribution/PensionContributions.scala
- app/uk/gov/hmrc/selfassessmentapi/repositories/SelfAssessmentRepository.scala
- func/uk/gov/hmrc/selfassessmentapi/TaxYearValidationSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/domain/pensioncontribution/PensionContributionSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/repositories/SelfAssessmentRepositorySpec.scala
- Modify the `PensionContributions` class to include a new `pensionSavings field`.
- Add a class, `PensionSavings` that is used to hold information about savings in excess of the annual allowance.
> [MTDSA-559] Collect excess pension contribution information.

- app/uk/gov/hmrc/selfassessmentapi/services/live/calculation/steps/SelfEmploymentProfitCalculation.scala
- test/uk/gov/hmrc/selfassessmentapi/domain/LiabilitySpec.scala
- test/uk/gov/hmrc/selfassessmentapi/services/live/calculation/steps/EmploymentIncomeCalculationSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/services/live/calculation/steps/FurnishedHolidayLettingsProfitCalculationSpec.scala
- Add some additional tests to verify the overall JSON structure.
> [MTDSA-571] Simplify liability testing.

- app/uk/gov/hmrc/selfassessmentapi/domain/selfemployment/Allowances.scala
- app/uk/gov/hmrc/selfassessmentapi/domain/selfemployment/SourceType.scala
- app/uk/gov/hmrc/selfassessmentapi/repositories/live/SelfEmploymentRepository.scala
- test/uk/gov/hmrc/selfassessmentapi/domain/selfemployment/AllowancesSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/repositories/live/SelfEmploymentRepositorySpec.scala
- test/uk/gov/hmrc/selfassessmentapi/services/live/calculation/steps/SelfEmploymentProfitCalculationSpec.scala
> [MTDSA-562] Remove the Restricted Capital Allowance type from Self-Employment

- app/uk/gov/hmrc/selfassessmentapi/domain/selfemployment/Expense.scala
- test/uk/gov/hmrc/selfassessmentapi/domain/selfemployment/ExpenseSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/services/live/calculation/steps/SelfEmploymentProfitCalculationSpec.scala
> [MTDSA-563] Rename CISPayments to CISPaymentsToSubcontractors.

- app/uk/gov/hmrc/selfassessmentapi/controllers/ErrorResponses.scala
- app/uk/gov/hmrc/selfassessmentapi/controllers/live/TaxYearDiscoveryController.scala
- app/uk/gov/hmrc/selfassessmentapi/controllers/sandbox/TaxYearDiscoveryController.scala
- app/uk/gov/hmrc/selfassessmentapi/services/SwitchedTaxYearProperties.scala
- app/uk/gov/hmrc/selfassessmentapi/services/live/TaxYearPropertiesService.scala
- app/uk/gov/hmrc/selfassessmentapi/services/sandbox/TaxYearPropertiesService.scala
- func/uk/gov/hmrc/selfassessmentapi/TaxYearValidationSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/services/live/TaxYearPropertiesServiceSpec.scala
> [MTDSA-578] Return HTTP error 400 when JSON is provided containing disabled properties.

- app/uk/gov/hmrc/selfassessmentapi/config/FeatureSwitch.scala
- app/uk/gov/hmrc/selfassessmentapi/controllers/api/furnishedholidaylettings/FurnishedHolidayLetting.scala
- app/uk/gov/hmrc/selfassessmentapi/controllers/sandbox/TaxYearDiscoveryController.scala
- app/uk/gov/hmrc/selfassessmentapi/services/sandbox/TaxYearPropertiesService.scala
- conf/application.conf
- func/uk/gov/hmrc/selfassessmentapi/FHLFeatureSwitchSpec.scala
- func/uk/gov/hmrc/selfassessmentapi/TaxYearPropertiesFeatureSwitchSpec.scala
- func/uk/gov/hmrc/selfassessmentapi/definition/DocumentationSpec.scala
- func/uk/gov/hmrc/selfassessmentapi/live/LiabilityControllerSpec.scala
- func/uk/gov/hmrc/selfassessmentapi/live/SelfAssessmentDiscoveryControllerSpec.scala
- func/uk/gov/hmrc/selfassessmentapi/live/SourceControllerSpec.scala
- func/uk/gov/hmrc/selfassessmentapi/live/SummaryControllerSpec.scala
- func/uk/gov/hmrc/selfassessmentapi/sandbox/SelfAssessmentDiscoveryControllerSpec.scala
- func/uk/gov/hmrc/selfassessmentapi/sandbox/SourceControllerSpec.scala
- func/uk/gov/hmrc/selfassessmentapi/sandbox/SummaryControllerSpec.scala
- Disable all tax year properties and employments.
> [SA|JTH] Introduce feature switching for UK and EEA furnished holiday lettings.

- app/uk/gov/hmrc/selfassessmentapi/controllers/api/FeatureSwitchedTaxYearProperties.scala
- app/uk/gov/hmrc/selfassessmentapi/controllers/definition/DocumentationController.scala
- app/uk/gov/hmrc/selfassessmentapi/controllers/definition/SelfAssessmentApiDefinition.scala
- app/uk/gov/hmrc/selfassessmentapi/controllers/live/TaxYearDiscoveryController.scala
- app/uk/gov/hmrc/selfassessmentapi/controllers/sandbox/TaxYearDiscoveryController.scala
- app/uk/gov/hmrc/selfassessmentapi/views/discoverTaxYear.scala.xml
- app/uk/gov/hmrc/selfassessmentapi/views/partials/taxYearPropertiesWriteRequest.scala.xml
- conf/application.conf
> [SA|JTH] Add switching for the tax year properties documentation.

- app/uk/gov/hmrc/selfassessmentapi/controllers/api/SelfEmploymentIncome.scala
- app/uk/gov/hmrc/selfassessmentapi/controllers/api/UkPropertyIncome.scala
- app/uk/gov/hmrc/selfassessmentapi/controllers/api/package.scala
- app/uk/gov/hmrc/selfassessmentapi/repositories/TypedSourceRepository.scala
- app/uk/gov/hmrc/selfassessmentapi/repositories/domain/Employment.scala
- app/uk/gov/hmrc/selfassessmentapi/repositories/domain/FurnishedHolidayLettings.scala
- app/uk/gov/hmrc/selfassessmentapi/repositories/domain/UKProperties.scala
- app/uk/gov/hmrc/selfassessmentapi/repositories/domain/UnearnedIncome.scala
- conf/definition.routes
- func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
- project/MicroService.scala
- test/uk/gov/hmrc/selfassessmentapi/Generators.scala
- test/uk/gov/hmrc/selfassessmentapi/MongoEmbeddedDatabase.scala
- test/uk/gov/hmrc/selfassessmentapi/TestApplication.scala
- test/uk/gov/hmrc/selfassessmentapi/controllers/api/JsonSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/controllers/api/LiabilitySpec.scala
- test/uk/gov/hmrc/selfassessmentapi/controllers/definition/SelfAssessmentApiDefinitionSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/jobs/DeleteExpiredDataJobSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/repositories/JobHistoryRepositorySpec.scala
- test/uk/gov/hmrc/selfassessmentapi/repositories/live/EmploymentRepositorySpec.scala
- test/uk/gov/hmrc/selfassessmentapi/services/DeleteExpiredDataServiceSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/services/live/calculation/LiabilityServiceSpec.scala
- Refactor code that was causing compilation to fail with the strict settings enabled.
> Enable strict compiler settings.

- app/uk/gov/hmrc/selfassessmentapi/repositories/domain/calculations/PensionSavingsCharges.scala
- test/uk/gov/hmrc/selfassessmentapi/repositories/domain/calculations/PensionSavingsChargesSpec.scala
> The excess of annual pension allowance should be rounded up before the tax band calculations.

- app/uk/gov/hmrc/selfassessmentapi/repositories/domain/TaxBand.scala
- test/uk/gov/hmrc/selfassessmentapi/repositories/domain/calculations/TaxBandSpec.scala
- Add a new test suite for the TaxBand classes.
> [JTH][MTDSA-597] The upper bounds for basic and higher rate tax bands should be rounded upwards.

- app/uk/gov/hmrc/selfassessmentapi/services/DeleteExpiredDataService.scala
- test/uk/gov/hmrc/selfassessmentapi/services/DeleteExpiredDataServiceSpec.scala
> [JTH][MTDSA-620] Add missing repositories to the DeleteExpiredData job.

- app/uk/gov/hmrc/selfassessmentapi/repositories/SelfAssessmentRepository.scala
- test/uk/gov/hmrc/selfassessmentapi/repositories/SelfAssessmentRepositorySpec.scala
- test/uk/gov/hmrc/selfassessmentapi/repositories/domain/builders/TaxYearPropertiesBuilder.scala
- test/uk/gov/hmrc/selfassessmentapi/repositories/domain/calculations/DeductionsSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/repositories/domain/calculations/DividendsSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/repositories/domain/calculations/NonSavingsSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/repositories/domain/calculations/PensionSavingsChargesSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/repositories/domain/calculations/SavingsSpec.scala
- Add tests to check all tax year properties are correctly persisted.
> [JTH][MTDSA-613] Persist all tax year properties.

- test/uk/gov/hmrc/selfassessmentapi/services/DeleteExpiredDataServiceSpec.scala
> Split tests into smaller units to be able to identify exactly where an operation fails.

- public/api/conf/1.0/application.raml
- public/api/conf/1.0/examples/uk-property/AnnualSummary.json
- public/api/conf/1.0/examples/uk-property/Period.json
- public/api/conf/1.0/examples/uk-property/errors/AnnualSummary_INVALID_REQUEST.json
- public/api/conf/1.0/schemas/uk-property/Adjustments.json
- public/api/conf/1.0/schemas/uk-property/Allowances.json
- public/api/conf/1.0/schemas/uk-property/AnnualSummary.json
- public/api/conf/1.0/schemas/uk-property/Period.json
> MTDSA-701 UK property annual summary

- app/uk/gov/hmrc/selfassessmentapi/resources/PropertiesResource.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/PropertiesResourceSpec.scala
> Fail with HTTP 409 with empty response when creating a second UK

- app/uk/gov/hmrc/selfassessmentapi/services/DividendsAnnualSummaryService.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/DividendsAnnualSummaryResourceSpec.scala
- Modify Dividends to return empty JSON when no dividends are found for a tax year.
> [JTH][MTDSA-688] Change code returned by DividenedsAnnualSummaryResponse.

- public/api/conf/1.0/application.raml
- Fixup instances of "self employment" which should be
"self-employment".
> [JTH] Modify group names to be sentence-case.

- app/uk/gov/hmrc/selfassessmentapi/domain/SelfEmployment.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/models/ErrorCode.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/models/selfemployment/SelfEmployment.scala
- app/uk/gov/hmrc/selfassessmentapi/services/SelfEmploymentsService.scala
- conf/SICs.txt
- func/uk/gov/hmrc/selfassessmentapi/featureswitch/SelfEmploymentAnnualSummaryFeatureSwitchSpec.scala
- func/uk/gov/hmrc/selfassessmentapi/featureswitch/SelfEmploymentPeriodicSummaryFeatureSwitchSpec.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentsResourceSpec.scala
- public/api/conf/1.0/application.raml
- public/api/conf/1.0/examples/self-employment/SelfEmployment.json
- public/api/conf/1.0/examples/self-employment/SelfEmployments.json
- public/api/conf/1.0/schemas/SelfEmployment.json
- public/api/conf/1.0/schemas/SelfEmployment_Without_ID.json
- test/uk/gov/hmrc/selfassessmentapi/repositories/SelfEmploymentRepositorySpec.scala
- test/uk/gov/hmrc/selfassessmentapi/resources/Jsons.scala
- test/uk/gov/hmrc/selfassessmentapi/resources/models/selfemployment/SelfEmploymentSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/services/DeleteExpiredDataServiceSpec.scala
- Update documentation for self-employments.
- Add complete list of UK 2007 SICs.
> [JTH][MTDSA-760] Update Self-Employment resource to include additional fields.

- public/api/conf/1.0/schemas/DIV_AnnualSummary.json
- public/api/conf/1.0/schemas/Expense.json
- public/api/conf/1.0/schemas/Income.json
- public/api/conf/1.0/schemas/SavingsAccount.json
- public/api/conf/1.0/schemas/SavingsAccount_AnnualSummary.json
- public/api/conf/1.0/schemas/SavingsAccount_Without_ID.json
- public/api/conf/1.0/schemas/SelfEmployment.json
- public/api/conf/1.0/schemas/SelfEmployment_Create_Without_ID.json
- public/api/conf/1.0/schemas/SelfEmployment_Without_ID.json
- public/api/conf/1.0/schemas/SimpleExpense.json
- public/api/conf/1.0/schemas/SimpleIncome.json
- public/api/conf/1.0/schemas/TaxCalculation.json
- public/api/conf/1.0/schemas/self-employment/Adjustments.json
- public/api/conf/1.0/schemas/self-employment/Allowances.json
- public/api/conf/1.0/schemas/uk-properties/Adjustments.json
- public/api/conf/1.0/schemas/uk-properties/fhl/Allowances.json
- public/api/conf/1.0/schemas/uk-properties/other/Allowances.json
- Remove invalid format 'money' and replace it with 'multipleOf: 0.01'
- Remove invalid format 'alphanumeric'
> [MTDSA-901] Specify correct format for values in Json schemas

- app/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentsResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/models/selfemployment/SelfEmploymentUpdate.scala
- app/uk/gov/hmrc/selfassessmentapi/services/SelfEmploymentsService.scala
- conf/live.routes
- func/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentsResourceSpec.scala
- public/api/conf/1.0/application.raml
- public/api/conf/1.0/examples/self-employment/SelfEmploymentCreate.json
- public/api/conf/1.0/examples/self-employment/SelfEmploymentUpdate.json
- public/api/conf/1.0/examples/self-employment/SelfEmployments.json
- public/api/conf/1.0/schemas/SelfEmployment.json
- public/api/conf/1.0/schemas/SelfEmployment_Update.json
- public/api/conf/1.0/schemas/SelfEmployment_Without_ID.json
- resources/SICs.txt
- test/uk/gov/hmrc/selfassessmentapi/resources/Jsons.scala
- test/uk/gov/hmrc/selfassessmentapi/resources/models/selfemployment/SelfEmploymentSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/resources/models/selfemployment/SelfEmploymentUpdateSpec.scala
- Implement new SelfEmploymentUpdate type that contains a subset of the fields contained in SelfEmployment.
- Add/modify tests.
> [MTDSA-719] Enable self-employment update.

- app/uk/gov/hmrc/selfassessmentapi/connectors/package.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentAnnualSummaryResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentObligationsResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentPeriodResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentsResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/TaxCalculationResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/TaxCalculationResponse.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/TaxCalculationResourceSpec.scala
- public/api/conf/1.0/application.raml
- Return 404 when the user submits an invalid calculation ID.
- Replace usages of 'if' in self-employment resources with match.
> Add debug logging for DES requests.

- app/uk/gov/hmrc/selfassessmentapi/models/selfemployment/SelfEmployment.scala
- app/uk/gov/hmrc/selfassessmentapi/models/selfemployment/SelfEmploymentRetrieve.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/SelfEmploymentResponse.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentsResourceSpec.scala
- public/api/conf/1.0/schemas/SelfEmployment.json
- public/api/conf/1.0/schemas/SelfEmployment_Without_ID.json
- test/uk/gov/hmrc/selfassessmentapi/models/selfemployment/SelfEmploymentRetrieveSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/models/selfemployment/SelfEmploymentSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/resources/Jsons.scala
The following fields are now optional:
- commencementDate
- businessDescription
- businessAddressLineOne
- businessPostcode
> Change select self-employment fields to be optional.

- app/uk/gov/hmrc/selfassessmentapi/resources/Binders.scala
- test/uk/gov/hmrc/selfassessmentapi/resources/BindersSpec.scala
- Remove all spaces in provided NINOs.
- Validate against both HMRC domain and DES NINO regex.
> Add DES NINO validation.

- app/uk/gov/hmrc/selfassessmentapi/models/ErrorCode.scala
- app/uk/gov/hmrc/selfassessmentapi/models/Validation.scala
- app/uk/gov/hmrc/selfassessmentapi/models/properties/PropertiesPeriod.scala
- app/uk/gov/hmrc/selfassessmentapi/models/selfemployment/Expenses.scala
- app/uk/gov/hmrc/selfassessmentapi/models/selfemployment/Incomes.scala
- app/uk/gov/hmrc/selfassessmentapi/models/selfemployment/SelfEmploymentPeriod.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentPeriodResourceSpec.scala
- public/api/conf/1.0/application.raml
- test/uk/gov/hmrc/selfassessmentapi/models/ExpenseSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/models/Generators.scala
- test/uk/gov/hmrc/selfassessmentapi/models/properties/PropertiesPeriodSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/models/selfemployment/ExpensesSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/models/selfemployment/SelfEmploymentPeriodSpec.scala
- Reject periodic summary updates of Self-Employments and UK Properties with no incomes or expenses
- Update documentation
> [MTDSA-1008] Fail null submissions of periodic summaries

- app/uk/gov/hmrc/selfassessmentapi/connectors/PropertiesPeriodConnector.scala
- app/uk/gov/hmrc/selfassessmentapi/connectors/SelfEmploymentConnector.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/PropertiesAnnualSummaryResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/PropertiesObligationsResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/PropertiesPeriodResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/ObligationsResponse.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/PropertiesAnnualSummaryResponse.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/PropertiesPeriodResponse.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/PropertiesResponse.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/Response.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/SelfEmploymentAnnualSummaryResponse.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/SelfEmploymentPeriodResponse.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/SelfEmploymentResponse.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/TaxCalculationResponse.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/PropertiesPeriodResourceSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/resources/wrappers/ResponseSpec.scala
Refactor DES response filter and response data types.
> [MTDSA-1026] Log error responses from DES

- .travis.yml
- project/MicroService.scala
Upgrade to the latest maintenance version of Scala 2.11.x from earlier patch version 2.11.8.
> Upgrade to Scala 2.11.11

- app/uk/gov/hmrc/selfassessmentapi/connectors/BusinessDetailsConnector.scala
- app/uk/gov/hmrc/selfassessmentapi/connectors/ObligationsConnector.scala
- app/uk/gov/hmrc/selfassessmentapi/connectors/PropertiesAnnualSummaryConnector.scala
- app/uk/gov/hmrc/selfassessmentapi/connectors/PropertiesConnector.scala
- app/uk/gov/hmrc/selfassessmentapi/connectors/PropertiesPeriodConnector.scala
- app/uk/gov/hmrc/selfassessmentapi/connectors/SelfEmploymentAnnualSummaryConnector.scala
- app/uk/gov/hmrc/selfassessmentapi/connectors/SelfEmploymentConnector.scala
- app/uk/gov/hmrc/selfassessmentapi/connectors/SelfEmploymentPeriodConnector.scala
- app/uk/gov/hmrc/selfassessmentapi/connectors/TaxCalculationConnector.scala
- app/uk/gov/hmrc/selfassessmentapi/connectors/package.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/BusinessDetailsResponse.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/ObligationsResponse.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/PropertiesAnnualSummaryResponse.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/PropertiesResponse.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/SelfEmploymentAnnualSummaryResponse.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/SelfEmploymentPeriodResponse.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/SelfEmploymentResponse.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/TaxCalculationResponse.scala
- project/build.properties
Refactor connectors to remove implicit conversions from HttpResponse to Response.
> [MTDSA-1036] Remove implicit conversion from HttpResponse to Response

- app/uk/gov/hmrc/selfassessmentapi/contexts/AuthContext.scala
- app/uk/gov/hmrc/selfassessmentapi/models/audit/AuditPayload.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/BanksAnnualSummaryResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/BanksResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/BaseResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/DividendsAnnualSummaryResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/PropertiesAnnualSummaryResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/PropertiesPeriodResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentAnnualSummaryResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentPeriodResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/TaxCalculationResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/Response.scala
- app/uk/gov/hmrc/selfassessmentapi/services/AuthenticationService.scala
- test/uk/gov/hmrc/selfassessmentapi/models/audit/AuditPayloadSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/resources/wrappers/ResponseSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/services/AuditServiceSpec.scala
- Update tests to include new payload field.
> [MTDSA-1053] Add the requester's affinityGroup to audit payloads.

- conf/released.routes
- public/api/conf/1.0/application.raml
- Retrieve self-employment obligations
- Retrieve property obligations
- Create other update period
- Update other annual summary
- Create FHL update period
- Update FHL annual summary
> [MTDSA-1054] Remove endpoints for initial release.

- app/uk/gov/hmrc/selfassessmentapi/config/microserviceGlobal.scala
- func/uk/gov/hmrc/selfassessmentapi/SetContentTypeFilterSpec.scala
- func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
This is a workaround for the WSO2 issue https://jira.tools.tax.service.gov.uk/browse/APSR-87.
> [MTDSA-1080] Add Play filter to set content type to json on the response

- app/uk/gov/hmrc/selfassessmentapi/resources/PropertiesObligationsResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentObligationsResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/package.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/BusinessDetailsResponse.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/ObligationsResponse.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/PropertiesAnnualSummaryResponse.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/PropertiesPeriodResponse.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/PropertiesResponse.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/SelfEmploymentAnnualSummaryResponse.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/SelfEmploymentPeriodResponse.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/SelfEmploymentResponse.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/TaxCalculationResponse.scala
- app/uk/gov/hmrc/selfassessmentapi/services/MtdRefLookupService.scala
- Change log level to error from warn in obligation resources.
> [MTDSA-1081] Add JSON details to DES response error logging.

- app/uk/gov/hmrc/selfassessmentapi/config/microserviceGlobal.scala
- app/uk/gov/hmrc/selfassessmentapi/connectors/SelfEmploymentStatementConnector.scala
- app/uk/gov/hmrc/selfassessmentapi/models/ErrorCode.scala
- app/uk/gov/hmrc/selfassessmentapi/models/ErrorResult.scala
- app/uk/gov/hmrc/selfassessmentapi/models/Errors.scala
- app/uk/gov/hmrc/selfassessmentapi/models/Period.scala
- app/uk/gov/hmrc/selfassessmentapi/models/audit/AuditDetail.scala
- app/uk/gov/hmrc/selfassessmentapi/models/des/DesError.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/Binders.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentStatementResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/package.scala
- conf/live.routes
- func/uk/gov/hmrc/selfassessmentapi/SelfAssessmentEndOfPeriodStatementSpec.scala
- func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
- project/MicroServiceBuild.scala
- project/plugins.sbt
- public/api/conf/1.0/application.raml
- public/api/conf/1.0/scenarios/declaration-scenarios.md
> Modify SE EOPS submit endpoint to use accounting period and error message changes

- app/uk/gov/hmrc/selfassessmentapi/connectors/CrystallisationConnector.scala
- app/uk/gov/hmrc/selfassessmentapi/connectors/SelfEmploymentStatementConnector.scala
- app/uk/gov/hmrc/selfassessmentapi/models/des/selfemployment/RequestDateTime.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/BaseResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/CrystallisationResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentStatementResource.scala
> [MTDSA-1299] [CK] Pass RequestDateTimestamp from API platform to DES.

- app/uk/gov/hmrc/selfassessmentapi/models/Errors.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentStatementResource.scala
- func/uk/gov/hmrc/selfassessmentapi/SelfAssessmentEndOfPeriodStatementSpec.scala
> [MTDSA-1301] [CK] Add start date validation check for submitting EOPS.

- app/uk/gov/hmrc/selfassessmentapi/config/microserviceGlobal.scala
- app/uk/gov/hmrc/selfassessmentapi/models/ErrorCode.scala
- func/uk/gov/hmrc/selfassessmentapi/SecuritySpec.scala
- func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
- func/uk/gov/hmrc/support/Http.scala
> [MTDSA-1231] Fix disclosure of internals on invalid JSON

- app/uk/gov/hmrc/selfassessmentapi/connectors/PropertiesConnector.scala
- app/uk/gov/hmrc/selfassessmentapi/models/des/properties/Properties.scala
- app/uk/gov/hmrc/selfassessmentapi/models/properties/NewProperties.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/PropertiesResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentStatementResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/package.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/DesJsons.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/PropertiesResourceSpec.scala
- func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
- public/api/conf/1.0/examples/uk-properties/UkProperties.json
- public/api/conf/1.0/schemas/UkProperties.json
- test/uk/gov/hmrc/selfassessmentapi/models/AccountingTypeSpec.scala
> Display accounting period when viewing UK property business details

- app/uk/gov/hmrc/selfassessmentapi/models/Errors.scala
- app/uk/gov/hmrc/selfassessmentapi/models/des/DesError.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentStatementResource.scala
- conf/live.routes
- func/uk/gov/hmrc/selfassessmentapi/SelfAssessmentEndOfPeriodStatementSpec.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/DesJsons.scala
- func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
- public/api/conf/1.0/application.raml
- public/api/conf/1.0/scenarios/declaration-scenarios.md
> [MTDSA-1325] Update SE EOPS validation rules

- app/uk/gov/hmrc/selfassessmentapi/models/des/PropertiesAnnualSummary.scala
- app/uk/gov/hmrc/selfassessmentapi/models/properties/FHLPropertiesAdjustments.scala
- app/uk/gov/hmrc/selfassessmentapi/models/properties/PropertiesAnnualSummary.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/DesJsons.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/PropertiesAnnualSummaryResourceSpec.scala
- public/api/conf/1.0/examples/uk-properties/fhl/AnnualSummary.json
- public/api/conf/1.0/schemas/uk-properties/Adjustments.json
- test/uk/gov/hmrc/selfassessmentapi/models/properties/FHLPropertiesAdjustmentsSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/models/properties/PropertiesAnnualSummarySpec.scala
- test/uk/gov/hmrc/selfassessmentapi/resources/Jsons.scala
> [MTDSA-1216] Add element to FHL annual allowances & adjustment

- public/api/conf/1.0/schemas/UK_PROP_FHL_AnnualSummary.json
- public/api/conf/1.0/schemas/UK_PROP_OTHER_AnnualSummary.json
- public/api/conf/1.0/schemas/uk-properties/fhl/Adjustments.json
- public/api/conf/1.0/schemas/uk-properties/other/Adjustments.json
> [MTDSA-1216] separate adjustments schemas for FHL/other property annual summaries

- app/uk/gov/hmrc/selfassessmentapi/models/des/properties/PropertiesPeriod.scala
- app/uk/gov/hmrc/selfassessmentapi/models/properties/PropertiesPeriod.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/PropertiesPeriodResource.scala
- func/uk/gov/hmrc/selfassessmentapi/AuthorisationServiceSpec.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/DesJsons.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/PropertiesPeriodResourceSpec.scala
- func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
- public/api/conf/1.0/examples/uk-properties/other/Period.json
- public/api/conf/1.0/examples/uk-properties/other/Period2.json
- public/api/conf/1.0/examples/uk-properties/other/UpdatePeriod.json
- public/api/conf/1.0/examples/uk-properties/other/UpdatePeriod2.json
- public/api/conf/1.0/schemas/uk-properties/other/OtherExpenses.json
- test/uk/gov/hmrc/selfassessmentapi/models/properties/PropertiesPeriodSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/resources/Jsons.scala
> Mtdsa 1145

- app/uk/gov/hmrc/selfassessmentapi/models/Errors.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentStatementResource.scala
- func/uk/gov/hmrc/selfassessmentapi/SelfAssessmentEndOfPeriodStatementSpec.scala
- public/api/conf/1.0/application.raml
> MTDSA-1345 - [RA] Correct error scenario for Submit SE EOPS

- func/uk/gov/hmrc/selfassessmentapi/resources/DesJsons.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/PropertiesPeriodResourceSpec.scala
- func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/resources/Jsons.scala
> MTDSA-1179-80 Submit consolidated expenses for Other and FHL

- app/uk/gov/hmrc/selfassessmentapi/models/des/PropertiesAnnualSummary.scala
- app/uk/gov/hmrc/selfassessmentapi/models/des/properties/PropertiesAnnualSummary.scala
- app/uk/gov/hmrc/selfassessmentapi/models/properties/OtherPropertiesAllowances.scala
- app/uk/gov/hmrc/selfassessmentapi/models/properties/PropertiesAnnualSummary.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/PropertiesAnnualSummaryResourceSpec.scala
- public/api/conf/1.0/examples/uk-properties/other/AnnualSummary.json
- public/api/conf/1.0/schemas/uk-properties/other/Allowances.json
- test/uk/gov/hmrc/selfassessmentapi/models/properties/OtherPropertiesAllowancesSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/models/properties/PropertiesAnnualSummarySpec.scala
- test/uk/gov/hmrc/selfassessmentapi/resources/Jsons.scala
> MTDSA-1327 and MTDSA-1328 - Remove BPRA field

- app/uk/gov/hmrc/selfassessmentapi/config/AppContext.scala
- app/uk/gov/hmrc/selfassessmentapi/connectors/PropertiesPeriodStatementConnector.scala
- app/uk/gov/hmrc/selfassessmentapi/models/Errors.scala
- app/uk/gov/hmrc/selfassessmentapi/models/des/PropertiesAnnualSummary.scala
- app/uk/gov/hmrc/selfassessmentapi/models/des/properties/PropertiesAnnualSummary.scala
- app/uk/gov/hmrc/selfassessmentapi/models/properties/OtherPropertiesAllowances.scala
- app/uk/gov/hmrc/selfassessmentapi/models/properties/PropertiesAnnualSummary.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/PropertiesPeriodStatementResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/utils/ResourceHelper.scala
- conf/application.conf
- conf/live.routes
- func/uk/gov/hmrc/selfassessmentapi/PropertiesPeriodEndOfPeriodStatementSpec.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/PropertiesAnnualSummaryResourceSpec.scala
- func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
- project/MicroServiceBuild.scala
- public/api/conf/1.0/application.raml
- public/api/conf/1.0/examples/uk-properties/Declaration.json
- public/api/conf/1.0/examples/uk-properties/other/AnnualSummary.json
- public/api/conf/1.0/schemas/Declaration.json
- public/api/conf/1.0/schemas/uk-properties/other/Allowances.json
- test/uk/gov/hmrc/selfassessmentapi/models/properties/OtherPropertiesAllowancesSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/models/properties/PropertiesAnnualSummarySpec.scala
- test/uk/gov/hmrc/selfassessmentapi/resources/BaseResourceSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/resources/Jsons.scala
- test/uk/gov/hmrc/selfassessmentapi/resources/PropertiesPeriodStatementResourceSpec.scala
MTDSA-1252 Submit EOP unit and func tests
MTDSA-1252 Submit EOP unit and func tests
Remove BPRA from 'Get/Submit a non-FHL UK Property Business Annual Summary' API
remove BPRA from RAML docs
fixed des model
MTDSA-1252 Submit EOPs for UK Property Business
> Submit EOP statment for UK Property

- app/uk/gov/hmrc/selfassessmentapi/controllers/definition/ApiDefinition.scala
- app/uk/gov/hmrc/selfassessmentapi/controllers/definition/SelfAssessmentApiDefinition.scala
- conf/application.conf
- public/api/conf/1.0/application.raml
- public/api/conf/1.0/docs/crystallisation-endpoint.md
- public/api/conf/1.0/docs/intent-to-crystallise.md
> [MTDSA-1341]  Align self-assessment-api to new API Platform statuses

- app/uk/gov/hmrc/selfassessmentapi/models/selfemployment/SelfEmployment.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentAnnualSummaryResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentsResource.scala
> remove TODO / FIX ME - MTDSA-1355

- public/api/conf/1.0/application.raml
> remove SIC Code error RAML

- app/uk/gov/hmrc/selfassessmentapi/connectors/GiftAidPaymentsConnector.scala
- app/uk/gov/hmrc/selfassessmentapi/models/ErrorCode.scala
- app/uk/gov/hmrc/selfassessmentapi/models/Errors.scala
- app/uk/gov/hmrc/selfassessmentapi/models/SourceType.scala
- app/uk/gov/hmrc/selfassessmentapi/models/des/giftaid/GiftAidPayments.scala
- app/uk/gov/hmrc/selfassessmentapi/models/giftaid/GiftAidPayments.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/GiftAidPaymentsResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/utils/ResourceHelper.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/GiftAidPaymentsResponse.scala
- conf/application.conf
- conf/live.routes
- func/uk/gov/hmrc/selfassessmentapi/resources/DesJsons.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/GiftAidPaymentsResourceFunctionalSpec.scala
- func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
- public/api/conf/1.0/application.raml
- public/api/conf/1.0/docs/gift-aid-payments.md
- public/api/conf/1.0/examples/gift-aid/GiftAidPayments.json
- public/api/conf/1.0/schemas/GiftAidPayments.json
- test/uk/gov/hmrc/selfassessmentapi/models/Generators.scala
- test/uk/gov/hmrc/selfassessmentapi/models/giftaid/GiftAidPaymentsSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/resources/BaseResourceSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/resources/GiftAidPaymentsResourceSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/resources/Jsons.scala
> [MTDSA-1292] Amend & View Annual Gift Aid Relief

- public/api/conf/1.0/application.raml
- public/api/conf/1.0/scenarios/gift-aid-amend-scenarios.md
- public/api/conf/1.0/scenarios/gift-aid-view-scenarios.md
> updated RAML for gift aid endpoints

- app/uk/gov/hmrc/selfassessmentapi/controllers/definition/ApiDefinition.scala
- app/uk/gov/hmrc/selfassessmentapi/controllers/definition/SelfAssessmentApiDefinition.scala
- app/uk/gov/hmrc/selfassessmentapi/models/des/selfemployment/SelfEmploymentAnnualSummary.scala
- app/uk/gov/hmrc/selfassessmentapi/models/selfemployment/Allowances.scala
- app/uk/gov/hmrc/selfassessmentapi/models/selfemployment/SelfEmploymentAnnualSummary.scala
- conf/application.conf
- func/uk/gov/hmrc/selfassessmentapi/resources/DesJsons.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentAnnualSummaryResourceSpec.scala
- public/api/conf/1.0/application.raml
- public/api/conf/1.0/docs/crystallisation-endpoint.md
- public/api/conf/1.0/docs/intent-to-crystallise.md
- public/api/conf/1.0/examples/self-employment/AnnualSummary_GET.json
- public/api/conf/1.0/examples/self-employment/AnnualSummary_PUT.json
- public/api/conf/1.0/schemas/self-employment/Allowances.json
- test/uk/gov/hmrc/selfassessmentapi/models/selfemployment/AllowancesSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/models/selfemployment/SelfEmploymentAnnualSummarySpec.scala
- test/uk/gov/hmrc/selfassessmentapi/resources/Jsons.scala
>  [MTDSA-1460] hotfix to add BPRA field back into SE annual summary 

- conf/live.routes
- func/uk/gov/hmrc/selfassessmentapi/resources/CrystallisationResourceSpec.scala
- public/api/conf/1.0/application.raml
- public/api/conf/1.0/removed-crystallisation-obligation.raml
> [remove-crys-obs] remove crystallisation obs endpoint for ET release

- CHANGELOG-ET.md
> Added v0.153.0 ET changelog

- app/uk/gov/hmrc/selfassessmentapi/connectors/ObligationsConnector.scala
- app/uk/gov/hmrc/selfassessmentapi/connectors/SelfEmploymentStatementConnector.scala
- app/uk/gov/hmrc/selfassessmentapi/models/des/CrystObligations.scala
- app/uk/gov/hmrc/selfassessmentapi/models/des/Obligations.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/PropertiesObligationsResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentObligationsResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentStatementResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/CrystObligationsResponse.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/ObligationsResponse.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/SelfEmploymentStatementResponse.scala
- conf/live.routes
- conf/logback-test.xml
- func/uk/gov/hmrc/selfassessmentapi/SelfAssessmentEndOfPeriodObligationsSpec.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/DesJsons.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/PropertiesObligationsResourceSpec.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentObligationsResourceSpec.scala
- func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/models/des/ObligationsSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/resources/wrappers/ObligationsResponseSpec.scala
> [MTDSA-1440] make obligations endpoints generic

- func/uk/gov/hmrc/selfassessmentapi/SelfAssessmentEndOfPeriodObligationsSpec.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/DesJsons.scala
- func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
> [MTDSA-1440] fix SA EOPS func tests

- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/SelfEmploymentStatementResponse.scala
- func/uk/gov/hmrc/selfassessmentapi/SelfAssessmentEndOfPeriodObligationsSpec.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/DesJsons.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/PropertiesObligationsResourceSpec.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentObligationsResourceSpec.scala
- func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
> [MTDSA-1440] add additional func tests for Obligations calls

- public/api/conf/1.0/application.raml
- public/api/conf/1.0/docs/sandbox.md
- public/api/conf/1.0/docs/testing.md
> MTDSA-1377 added new testing section

- project/MicroService.scala
- project/plugins.sbt
- test/uk/gov/hmrc/selfassessmentapi/MongoEmbeddedDatabase.scala
> MTDSA-1376 Added scoverage and fixed failing local test

- CHANGELOG-ET.md
- conf/logback-test.xml
- project/MicroService.scala
- public/api/conf/1.0/application.raml
- public/api/conf/1.0/examples/uk-properties/BISS/net_loss.json
- public/api/conf/1.0/examples/uk-properties/BISS/net_profit.json
- public/api/conf/1.0/scenarios/uk-properties-biss.md
- public/api/conf/1.0/schemas/uk-properties/BISS/BISS.json
> [MTDSA-1765] update documentation and changelog

- public/api/conf/1.0/application.raml
> [MTDSA-1765] update error codes

- app/uk/gov/hmrc/selfassessmentapi/config/AppContext.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/PropertiesPeriodResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentPeriodResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/PropertiesPeriodResponse.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/Response.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/SelfEmploymentPeriodResponse.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/PropertiesPeriodResourceSpec.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentPeriodResourceSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/resources/wrappers/SelfEmploymentPeriodResponseSpec.scala
> MTDSA-1641 Applied hotfix

- app/uk/gov/hmrc/selfassessmentapi/models/des/PropertiesAnnualSummary.scala
- app/uk/gov/hmrc/selfassessmentapi/models/properties/OtherPropertiesAllowances.scala
- app/uk/gov/hmrc/selfassessmentapi/models/properties/PropertiesAnnualSummary.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/DesJsons.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/PropertiesAnnualSummaryResourceSpec.scala
- public/api/conf/1.0/application.raml
- public/api/conf/1.0/examples/uk-properties/other/AnnualSummary.json
- public/api/conf/1.0/schemas/uk-properties/other/Allowances.json
- test/uk/gov/hmrc/selfassessmentapi/models/properties/OtherPropertiesAllowancesSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/models/properties/PropertiesAnnualSummarySpec.scala
- test/uk/gov/hmrc/selfassessmentapi/resources/Jsons.scala
- test/uk/gov/hmrc/selfassessmentapi/resources/PropertiesAnnualSummaryResourceSpec.scala
> [MTDSA-1754] Remove rentARoomExempt from non-fhl annual summary

- CHANGELOG-ET.md
> [MTDSA-1754] update changelog

- public/api/conf/1.0/application.raml
> [BISS-raml-update] add test only to BISS endpoint

- app/uk/gov/hmrc/selfassessmentapi/connectors/SelfEmploymentBISSConnector.scala
- app/uk/gov/hmrc/selfassessmentapi/httpparsers/HttpParser.scala
- app/uk/gov/hmrc/selfassessmentapi/httpparsers/SelfEmploymentBISSHttpParser.scala
- app/uk/gov/hmrc/selfassessmentapi/models/Errors.scala
- app/uk/gov/hmrc/selfassessmentapi/models/des/DesError.scala
- app/uk/gov/hmrc/selfassessmentapi/models/selfemployment/SelfEmploymentBISS.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentBISSResource.scala
- conf/application.conf
- conf/live.routes
- func/uk/gov/hmrc/selfassessmentapi/resources/DesJsons.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentBISSResourceFuncSpec.scala
- func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/connectors/ConnectorSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/connectors/SelfEmploymentBISSConnectorSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/fixtures/selfemployment/SelfEmploymentBISSFixture.scala
- test/uk/gov/hmrc/selfassessmentapi/httpparsers/SelfEmploymentBISSHttpParserSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/mocks/connectors/MockSelfEmploymentBISSConnector.scala
- test/uk/gov/hmrc/selfassessmentapi/models/selfemployment/SelfEmploymentBISSSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentBISSResourceSpec.scala
> MTDSA-1471 BISS for SE Business

- app/uk/gov/hmrc/selfassessmentapi/connectors/SelfEmploymentBISSConnector.scala
- app/uk/gov/hmrc/selfassessmentapi/models/Errors.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentBISSResource.scala
- app/uk/gov/hmrc/selfassessmentapi/services/SelfEmploymentBISSService.scala
- conf/live.routes
- func/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentBISSResourceFuncSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/mocks/services/MockSelfEmploymentBISSService.scala
- test/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentBISSResourceSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/services/SelfEmploymentBISSServiceSpec.scala
> MTDSA-1901 Add validation logic for self employment ID format

- CHANGELOG-ET.md
> update changelog for SE BISS

- CHANGELOG-ET.md
> Updated the change log for other property income

- app/uk/gov/hmrc/selfassessmentapi/repositories/BanksRepository.scala
- app/uk/gov/hmrc/selfassessmentapi/repositories/DividendsRepository.scala
- project/MicroServiceBuild.scala
- project/build.properties
- project/plugins.sbt
- test/uk/gov/hmrc/selfassessmentapi/repositories/BanksRepositorySpec.scala
- test/uk/gov/hmrc/selfassessmentapi/repositories/DividendsRepositorySpec.scala
- test/uk/gov/hmrc/selfassessmentapi/repositories/MtdReferenceRepositorySpec.scala
> Updated the dependencies and fix the tests for SA

- app/uk/gov/hmrc/selfassessmentapi/config/microserviceGlobal.scala
- app/uk/gov/hmrc/selfassessmentapi/models/EopsObligations.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentStatementResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/SelfEmploymentStatementResponse.scala
- func/uk/gov/hmrc/selfassessmentapi/SelfAssessmentEndOfPeriodObligationsSpec.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/DesJsons.scala
- project/MicroServiceBuild.scala
- test/uk/gov/hmrc/selfassessmentapi/resources/Jsons.scala
- test/uk/gov/hmrc/selfassessmentapi/resources/wrappers/SelfEmploymentStatementResponseSpec.scala
> [MTDSA-2222] update EOPS filter in SE StatementResponse

- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/CrystallisationIntentResponse.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/DesJsons.scala
> [MTDSA-2218] modify intent to crystallise resposne

- app/uk/gov/hmrc/selfassessmentapi/models/des/DesError.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/CrystallisationResource.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/DesJsons.scala
- func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
> [MTDSA-2219] map modified errors

- app/uk/gov/hmrc/selfassessmentapi/models/Errors.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/CrystallisationResource.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/CrystallisationResourceFuncSpec.scala
> [MTDSA-2197] update required intent to crystallise error message

- app/uk/gov/hmrc/selfassessmentapi/connectors/PropertiesPeriodConnector.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/PropertiesPeriodResourceSpec.scala
- func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
> [MTDSA-2231] update DES url

- app/uk/gov/hmrc/selfassessmentapi/models/des/selfemployment/SelfEmploymentPeriod.scala
- app/uk/gov/hmrc/selfassessmentapi/models/selfemployment/SelfEmploymentPeriodUpdate.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/SelfEmploymentPeriodResourceSpec.scala
> fix consolidated expenses bug on SE amend period

- app/uk/gov/hmrc/selfassessmentapi/connectors/SelfEmploymentStatementConnector.scala
- func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
> [MK] Remove trailing slash from SE EOPS Obs e/p

- app/uk/gov/hmrc/selfassessmentapi/connectors/TaxCalculationConnector.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/TaxCalculationResource.scala
- func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
> MTDSA-2278 Align Trigger Tax Calculation to DES API#16

- app/uk/gov/hmrc/selfassessmentapi/connectors/CrystallisationConnector.scala
- func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
> [MTDSA-2197] amend Crystallisation DES endpoint

- app/uk/gov/hmrc/selfassessmentapi/models/audit/AuditDetail.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/CrystallisationResource.scala
> MTDSA-2160 Created Explicit Audit at Intent to Crystallise

- app/uk/gov/hmrc/selfassessmentapi/connectors/PropertiesPeriodConnector.scala
- func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
> [MTDSA-2301] update DES URL for Create Property Update Period

- app/uk/gov/hmrc/selfassessmentapi/connectors/PropertiesPeriodConnector.scala
- func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
> [MTDSA-2301] update DES URL for Amend Property Update Period

- app/uk/gov/hmrc/selfassessmentapi/models/des/properties/PropertiesPeriod.scala
- app/uk/gov/hmrc/selfassessmentapi/models/properties/PropertiesPeriod.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/DesJsons.scala
> MTDSA-2302 Updated model as per des spec

- app/uk/gov/hmrc/selfassessmentapi/models/audit/AuditDetail.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/CrystallisationResource.scala
- app/uk/gov/hmrc/selfassessmentapi/services/AuditService.scala
> MTDSA-2161 Created Explicit Audit at Crystallisation

- app/uk/gov/hmrc/selfassessmentapi/models/Errors.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/PropertiesPeriodResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/Response.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/DesJsons.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/PropertiesPeriodResourceSpec.scala
- func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
> [MTDSA-2304] update error mappings for Create Property Update Period

- project/MicroService.scala
- project/MicroServiceBuild.scala
- project/plugins.sbt
> [MK] update microservice for new build

- app/uk/gov/hmrc/selfassessmentapi/connectors/PropertiesPeriodConnector.scala
- app/uk/gov/hmrc/selfassessmentapi/models/Errors.scala
- app/uk/gov/hmrc/selfassessmentapi/models/des/properties/PropertiesPeriod.scala
- app/uk/gov/hmrc/selfassessmentapi/models/properties/PropertiesPeriod.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/PropertiesPeriodResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/Response.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/DesJsons.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/PropertiesPeriodResourceSpec.scala
- func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
> [MK] revert create and amend update period changes

- app/uk/gov/hmrc/selfassessmentapi/models/des/properties/PropertiesPeriod.scala
- app/uk/gov/hmrc/selfassessmentapi/models/properties/PropertiesPeriod.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/DesJsons.scala
> MTDSA-2130 Updated the FHL model as per des spec

- app/uk/gov/hmrc/selfassessmentapi/connectors/PropertiesPeriodConnector.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/PropertiesPeriodResource.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/DesJsons.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/PropertiesPeriodResourceSpec.scala
> [MTDSA-2297] update error mappings to match old MTD responses

- app/uk/gov/hmrc/selfassessmentapi/resources/PropertiesPeriodResource.scala
> [MTDSA-2297] add additional logging

- app/uk/gov/hmrc/selfassessmentapi/resources/PropertiesPeriodResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/Response.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/PropertiesPeriodResourceSpec.scala
- func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
> [MTDSA-2343] align and update amend Property Update period

- .gitignore
- app/uk/gov/hmrc/selfassessmentapi/resources/CrystallisationResource.scala
- func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
> modified expected response status for crystallisation

- app/uk/gov/hmrc/selfassessmentapi/resources/PropertiesPeriodResource.scala
> [MTDSA-2343] modify correlationID signature

- app/uk/gov/hmrc/selfassessmentapi/resources/BaseResource.scala
> MTDSA-2266: Improved error context logging as suggested in PRA

- conf/released.routes
> added SE EOPS Obligations, and Crystallisation endpoints to released routes

- app/uk/gov/hmrc/selfassessmentapi/connectors/PropertiesBISSConnector.scala
- app/uk/gov/hmrc/selfassessmentapi/httpparsers/PropertiesBISSHttpParser.scala
- app/uk/gov/hmrc/selfassessmentapi/models/Errors.scala
- app/uk/gov/hmrc/selfassessmentapi/models/des/DesError.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/PropertiesBISSResource.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/DesJsons.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/PropertiesBISSResourceFuncSpec.scala
- func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/connectors/PropertiesBISSConnectorSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/httpparsers/PropertiesBISSHttpParserSpec.scala
- test/uk/gov/hmrc/selfassessmentapi/resources/PropertiesBISSResourceSpec.scala
> MTDSA-2450: Updated url and error scenarios as per des spec #1415

- app/uk/gov/hmrc/selfassessmentapi/resources/PropertiesAnnualSummaryResource.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/PropertiesAnnualSummaryResourceSpec.scala
- func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
> MTDSA-2345: Added propertyId into error log function in Properties Annual Summary

- app/uk/gov/hmrc/selfassessmentapi/resources/TaxCalculationResource.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/wrappers/TaxCalculationResponse.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/DesJsons.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/TaxCalculationResourceSpec.scala
- func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
> [MTDSA-2499] add extra logging for INVALID_REQUEST scenario for trigger tax calc

- project/MicroServiceBuild.scala
- project/plugins.sbt
> [MTDSA-2636] update dependencies

- app/uk/gov/hmrc/r2/selfassessmentapi/models/des/properties/PropertiesPeriod.scala
- app/uk/gov/hmrc/r2/selfassessmentapi/models/properties/PropertiesPeriod.scala
- func/uk/gov/hmrc/r2/selfassessmentapi/resources/PropertiesPeriodResourceSpec.scala
- test/uk/gov/hmrc/r2/selfassessmentapi/models/properties/PropertiesPeriodSpec.scala
- test/uk/gov/hmrc/r2/selfassessmentapi/resources/Jsons.scala
> MTDSA-2601 Added new fields to the model

- conf/released.routes
> MTDSA-2601: Added r2 routes to released.routes for prod

- app/uk/gov/hmrc/r2/selfassessmentapi/models/des/properties/PropertiesPeriod.scala
- app/uk/gov/hmrc/r2/selfassessmentapi/models/properties/PropertiesPeriod.scala
- test/uk/gov/hmrc/r2/selfassessmentapi/models/properties/PropertiesPeriodSpec.scala
- test/uk/gov/hmrc/r2/selfassessmentapi/resources/Jsons.scala
> Updated for get and amend

- app/uk/gov/hmrc/r2/selfassessmentapi/models/des/properties/PropertiesPeriod.scala
- app/uk/gov/hmrc/r2/selfassessmentapi/models/properties/PropertiesPeriod.scala
- test/uk/gov/hmrc/r2/selfassessmentapi/models/properties/PropertiesPeriodSpec.scala
> Added fields to the FHL properties period

- func/uk/gov/hmrc/r2/selfassessmentapi/resources/DesJsons.scala
- func/uk/gov/hmrc/r2/selfassessmentapi/resources/PropertiesPeriodResourceSpec.scala
- func/uk/gov/hmrc/r2/selfassessmentapi/support/BaseFunctionalSpec.scala
- test/uk/gov/hmrc/r2/selfassessmentapi/resources/Jsons.scala
> Updated FHL with the new routes

- app/uk/gov/hmrc/r2/selfassessmentapi/resources/PropertiesAnnualSummaryResource.scala
- conf/r2.routes
- func/uk/gov/hmrc/r2/selfassessmentapi/resources/PropertiesAnnualSummaryResourceSpec.scala
> [MTDSA-2683] added explicit fhl and other endpoints for r2

- README.md
- project/plugins.sbt
> MTDSA-2695 - Added dependency check plugins and updated README to reflect new tasks added

- app/uk/gov/hmrc/selfassessmentapi/models/Errors.scala
- app/uk/gov/hmrc/selfassessmentapi/resources/TaxCalculationResource.scala
- conf/live.routes
- conf/logback-test.xml
- func/uk/gov/hmrc/selfassessmentapi/resources/CrystallisationResourceFuncSpec.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/TaxCalculationResourceSpec.scala
- func/uk/gov/hmrc/support/BaseFunctionalSpec.scala
- func/uk/gov/hmrc/support/Http.scala
- test/uk/gov/hmrc/selfassessmentapi/resources/Jsons.scala
> [MTDSA-2726] override Retrieve Tax Calc to return 410 - RESOURCE_GONE

- app/uk/gov/hmrc/r2/selfassessmentapi/connectors/SelfEmploymentAnnualSummaryConnector.scala
- app/uk/gov/hmrc/r2/selfassessmentapi/models/Class4NicInfo.scala
- app/uk/gov/hmrc/r2/selfassessmentapi/models/des/selfemployment/SelfEmployment.scala
- app/uk/gov/hmrc/r2/selfassessmentapi/models/des/selfemployment/SelfEmploymentAnnualSummary.scala
- app/uk/gov/hmrc/r2/selfassessmentapi/models/selfemployment/Adjustments.scala
- app/uk/gov/hmrc/r2/selfassessmentapi/models/selfemployment/Allowances.scala
- app/uk/gov/hmrc/r2/selfassessmentapi/models/selfemployment/NonFinancials.scala
- app/uk/gov/hmrc/r2/selfassessmentapi/models/selfemployment/SelfEmployment.scala
- app/uk/gov/hmrc/r2/selfassessmentapi/models/selfemployment/SelfEmploymentAnnualSummary.scala
- app/uk/gov/hmrc/r2/selfassessmentapi/resources/SelfEmploymentAnnualSummaryResource.scala
- app/uk/gov/hmrc/r2/selfassessmentapi/resources/wrappers/SelfEmploymentAnnualSummaryResponse.scala
- conf/r2.routes
- func/uk/gov/hmrc/r2/selfassessmentapi/resources/DesJsons.scala
- func/uk/gov/hmrc/r2/selfassessmentapi/resources/SelfEmploymentAnnualSummaryResourceSpec.scala
- func/uk/gov/hmrc/r2/selfassessmentapi/support/BaseFunctionalSpec.scala
- test/uk/gov/hmrc/r2/selfassessmentapi/fixtures/selfemployment/des/AnnualSummaryFixture.scala
- test/uk/gov/hmrc/r2/selfassessmentapi/models/selfemployment/AdjustmentsSpec.scala
- test/uk/gov/hmrc/r2/selfassessmentapi/models/selfemployment/AllowancesSpec.scala
- test/uk/gov/hmrc/r2/selfassessmentapi/models/selfemployment/SelfEmploymentAnnualSummarySpec.scala
- test/uk/gov/hmrc/r2/selfassessmentapi/resources/Jsons.scala
> MTDSA 2708: Added tradingAllowance to self-employment annual summaries

- project/plugins.sbt
> MTDSA-2795: Upgrade play version to 2.5.19 due to security vulnerabilities

- app/uk/gov/hmrc/selfassessmentapi/models/des/selfemployment/SelfEmploymentAnnualSummary.scala
- app/uk/gov/hmrc/selfassessmentapi/models/selfemployment/SelfEmploymentAnnualSummary.scala
- func/uk/gov/hmrc/selfassessmentapi/resources/DesJsons.scala
- test/uk/gov/hmrc/selfassessmentapi/fixtures/selfemployment/des/AnnualSummaryFixture.scala
- test/uk/gov/hmrc/selfassessmentapi/models/selfemployment/SelfEmploymentAnnualSummarySpec.scala
- test/uk/gov/hmrc/selfassessmentapi/resources/Jsons.scala
> [MTDSA-2868] remove fields from SE Annual Summary

- project/MicroService.scala
> fix to MicroService.scala

- app/uk/gov/hmrc/r2/selfassessmentapi/models/des/PropertiesAnnualSummary.scala
- app/uk/gov/hmrc/r2/selfassessmentapi/models/properties/PropertiesAnnualSummary.scala
- func/uk/gov/hmrc/r2/selfassessmentapi/resources/DesJsons.scala
- test/uk/gov/hmrc/r2/selfassessmentapi/models/des/PropertiesAnnualSummarySpec.scala
- test/uk/gov/hmrc/r2/selfassessmentapi/resources/Jsons.scala
> [MTDSA-3105] Alignment of UK Property Annuals endpoints

- project/MicroServiceBuild.scala
> Updated ReactiveMongo to v6.4.0

- app/uk/gov/hmrc/r2/selfassessmentapi/models/des/selfemployment/SelfEmploymentAnnualSummary.scala
- app/uk/gov/hmrc/r2/selfassessmentapi/models/selfemployment/SelfEmploymentAnnualSummary.scala
- func/uk/gov/hmrc/r2/selfassessmentapi/resources/DesJsons.scala
- test/uk/gov/hmrc/r2/selfassessmentapi/fixtures/selfemployment/des/AnnualSummaryFixture.scala
- test/uk/gov/hmrc/r2/selfassessmentapi/models/selfemployment/SelfEmploymentAnnualSummarySpec.scala
> MTDSA-3101: Aligned fields in SE annuals for release 2

- test/uk/gov/hmrc/selfassessmentapi/resources/PropertiesPeriodStatementResourceSpec.scala
> MTDSA-3315 Fixed the unit tests

- project/MicroServiceBuild.scala
> Updated dependencies

- project/plugins.sbt
>   Updated dependencies

- app/router/services/CharitableGivingService.scala
- app/router/services/CrystallisationService.scala
- app/router/services/DividendsService.scala
- app/router/services/PropertyEopsDeclarationService.scala
- app/router/services/PropertyEopsObligationsService.scala
- app/router/services/SavingsAccountService.scala
- app/router/services/SelfEmploymentEopsDeclarationService.scala
- app/router/services/TaxCalcService.scala
- it/router/resources/CharitableGivingResourceISpec.scala
- it/router/resources/CrystallisationResourceISpec.scala
- it/router/resources/DividendsResourceISpec.scala
- it/router/resources/PropertyEopsDeclarationResourceISpec.scala
- it/router/resources/SavingsAccountResourceISpec.scala
- it/router/resources/SelfEmploymentEopsDeclarationResourceISpec.scala
- it/router/resources/TaxCalcResourceISpec.scala
- test/mocks/connectors/MockSavingsAccountConnector.scala
- test/router/services/CharitableGivingServiceSpec.scala
- test/router/services/CrystallisationServiceSpec.scala
- test/router/services/DividendsServiceSpec.scala
- test/router/services/PropertyEopsDeclarationServiceSpec.scala
- test/router/services/PropertyEopsObligationsServiceSpec.scala
- test/router/services/SavingsAccountServiceSpec.scala
- test/router/services/SelfEmploymentEopsDeclarationServiceSpec.scala
- test/router/services/TaxCalcServiceSpec.scala
Intentionally did not touch Crystallisation Obligations, ReleaseTwoService or SelfAssessmentService.
> [MTDSA-3541] Removed release 2 specific feature switches

- public/api/conf/2.0/application.raml
RAML changes for self employment obligations
> MTDSA-4235
